inastemp:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake ..
    - make
    - make test
  tags:
    - default

inastempclang:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CC=clang-3.5 CXX=clang++-3.5 cmake ..
    - make
    - make test
  tags:
    - clang

inastempclangsde:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CC=clang-3.5 CXX=clang++-3.5 cmake  -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_USE_AVX512KNL=ON ..
    - make
    - make test
  tags:
    - clang
    - sde

inastempgcc48:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CC=gcc-4.8 CXX=g++-4.8 cmake ..
    - make
    - make test
  tags:
    - gcc48

inastempsdep4p:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-p4p" -DINASTEMP_ISDE_UTESTS_ARGS="-p4p" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - sde

inastempsdemrm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-mrm" -DINASTEMP_ISDE_UTESTS_ARGS="-mrm" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - sde

inastempsdepnr:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-pnr" -DINASTEMP_ISDE_UTESTS_ARGS="-pnr" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - sde

inastempsdenhm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-nhm" -DINASTEMP_ISDE_UTESTS_ARGS="-nhm" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - sde

inastempsdewsm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-wsm" -DINASTEMP_ISDE_UTESTS_ARGS="-wsm" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - sde

inastempsdesnb:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-snb" -DINASTEMP_ISDE_UTESTS_ARGS="-snb" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - sde

inastempsdewsm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-ivb" -DINASTEMP_ISDE_UTESTS_ARGS="-ivb" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - sde

inastempsdehsw:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-hsw" -DINASTEMP_ISDE_UTESTS_ARGS="-hsw" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - sde


inastempgccsdecov:
  stage: test
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_WITH_PROF=ON ..
    - VERBOSE=1 make
    - VERBOSE=1 make lcov_clean
    - VERBOSE=1 make test
    - VERBOSE=1 make lcov_capture
    - VERBOSE=1 make lcov_html
  tags:
    - gcc
    - lcov
  artifacts:
    paths:
      - build/coverage/

pages:
  stage: deploy
  dependencies:
    - inastempgccsdecov
  script:
    - mkdir public
    - mv build/coverage/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - code-coverage
    - master
