image: berenger/inastemp

inastemp:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempclang:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1  CXX=clang++ cmake ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempclangsdeknl:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1  CXX=clang++ cmake  -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-knl" -DINASTEMP_ISDE_UTESTS_ARGS="-knl" -DINASTEMP_USE_AVX512KNL=ON -DARCH_NATIVE_FLAG="-march=knl" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempclangsdeskl:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1  CXX=clang++ cmake  -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-skx" -DINASTEMP_ISDE_UTESTS_ARGS="-skx" -DINASTEMP_USE_AVX512SKL=ON -DARCH_NATIVE_FLAG="-march=skylake" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdep4p:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-p4p" -DINASTEMP_ISDE_UTESTS_ARGS="-p4p" -DARCH_NATIVE_FLAG="-march=pentium4" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdemrm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-mrm" -DINASTEMP_ISDE_UTESTS_ARGS="-mrm" -DARCH_NATIVE_FLAG="" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdepnr:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-pnr" -DINASTEMP_ISDE_UTESTS_ARGS="-pnr" -DARCH_NATIVE_FLAG="" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdenhm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-nhm" -DINASTEMP_ISDE_UTESTS_ARGS="-nhm" -DARCH_NATIVE_FLAG="-march=nehalem" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdewsm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-wsm" -DINASTEMP_ISDE_UTESTS_ARGS="-wsm" -DARCH_NATIVE_FLAG="-march=westmere" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdesnb:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-snb" -DINASTEMP_ISDE_UTESTS_ARGS="-snb" -DARCH_NATIVE_FLAG="-march=sandybridge" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdeivb:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-ivb" -DINASTEMP_ISDE_UTESTS_ARGS="-ivb" -DARCH_NATIVE_FLAG="-march=ivybridge" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdehsw:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-hsw" -DINASTEMP_ISDE_UTESTS_ARGS="-hsw" -DARCH_NATIVE_FLAG="-march=haswell" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdeknl:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1  CXX=g++ cmake  -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-knl" -DINASTEMP_ISDE_UTESTS_ARGS="-knl" -DINASTEMP_USE_AVX512KNL=ON -DARCH_NATIVE_FLAG="knl" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempsdeskl:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1  CXX=g++ cmake  -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-skx" -DINASTEMP_ISDE_UTESTS_ARGS="-skx" -DINASTEMP_USE_AVX512SKL=ON -DARCH_NATIVE_FLAG="skl" ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium

inastempgccsdecov:
  stage: test
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_WITH_PROF=ON ..
    - VERBOSE=1 make
    - make test
  tags:
    - medium
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - inastempgccsdecov
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
