image: berenger/inastemp

inastemp:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake ..
    - make
    - make test
  tags:
    - medium

inastempclang:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1  CXX=clang++ cmake ..
    - make
    - make test
  tags:
    - medium

inastempclangsde:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1  CXX=clang++ cmake  -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_USE_AVX512KNL=ON ..
    - make
    - make test
  tags:
    - medium

inastempsdep4p:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-p4p" -DINASTEMP_ISDE_UTESTS_ARGS="-p4p" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - medium

inastempsdemrm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-mrm" -DINASTEMP_ISDE_UTESTS_ARGS="-mrm" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - medium

inastempsdepnr:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-pnr" -DINASTEMP_ISDE_UTESTS_ARGS="-pnr" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - medium

inastempsdenhm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-nhm" -DINASTEMP_ISDE_UTESTS_ARGS="-nhm" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - medium

inastempsdewsm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-wsm" -DINASTEMP_ISDE_UTESTS_ARGS="-wsm" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - medium

inastempsdesnb:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-snb" -DINASTEMP_ISDE_UTESTS_ARGS="-snb" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - medium

inastempsdewsm:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-ivb" -DINASTEMP_ISDE_UTESTS_ARGS="-ivb" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - medium

inastempsdehsw:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_ISDE_CPU_ARGS="-hsw" -DINASTEMP_ISDE_UTESTS_ARGS="-hsw" -DARCH_NATIVE_FLAG="" ..
    - make
    - make test
  tags:
    - medium



inastempgccsdecov:
  stage: test
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DINASTEMP_WITH_PROF=ON ..
    - VERBOSE=1 make
    - VERBOSE=1 make lcov_clean
    - VERBOSE=1 make test
    - VERBOSE=1 make lcov_capture
    - VERBOSE=1 make lcov_html
  tags:
    - medium
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - inastempgccsdecov
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
