inastemp:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake ..
    - make
    - make test
  tags:
    - default

inastempsde:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 cmake -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_USE_AVX512KNL=ON ..
    - make
    - make test
  tags:
    - sde

inastempclang:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CC=clang-3.5 CXX=clang++-3.5 cmake ..
    - make
    - make test
  tags:
    - clang

inastempclangsde:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CC=clang-3.5 CXX=clang++-3.5 cmake  -DINASTEMP_ISDE_CPU=ON -DINASTEMP_ISDE_UTESTS=ON -DINASTEMP_USE_AVX512KNL=ON ..
    - make
    - make test
  tags:
    - clang
    - sde

inastempgcc49:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CC=gcc-4.9 CXX=g++-4.9 cmake ..
    - make
    - make test
  tags:
    - gcc49
